import Head from 'next/head';
import Image from 'next/image';
import { groupBy } from '../helpers/helpers';
import { getRecords } from '../lib/airtable-api';
import styles from '../styles/Home.module.css';

export default function Home({ data }) {
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {Object.keys(data).map((key) => (
          <section key={key}>
            <h2>{key}</h2>
            <ol>
              {data[key].map((item) => (
                <li key={item.name}>
                  <a href={item.url}>{item.name}</a>
                </li>
              ))}
            </ol>
          </section>
        ))}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getStaticProps(context) {
  const records = await getRecords();
  const formattedRecords = groupBy(records, 'category');
  return {
    props: {
      data: formattedRecords,
    },
  };
}
